name: alok
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  simple_animations: ^5.0.0+3
  http:
  fluttertoast: ^8.0.8
  flutterwave_standard: 1.0.7
  toast: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.9
  flutter_dropdown: ^1.0.1+hotfix.1
  giffy_dialog: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
  assets:
   - assets/images/